### ISSUE TITLE
a 1:1 implementation of cw3-fixed-multisig

### ISSUE THREAD

**Issue by zorostang** [zorostang/snip3-fixed-multisig#1]
Dev Notes:
The cw3 reference contract is not structured the way it's usually done on Secret. For Example, see:
https://github.com/CosmWasm/cw-plus/blob/main/contracts/cw3-fixed-multisig/src/lib.rs vs.
https://github.com/scrtlabs/secret-template/blob/master/src/lib.rs

set_contract_version and cw-storage-plus not available in secret

set_contract_version - we recommend just ignore this reference (remove it). you won't be able to migrate the contract but that's fine for now. also this will probably become available when secret updates to cw1.0
cw-storage-plus - this could be refactored out - technically

**Comment by kent-3** [comment]
I've begun work on this and have hit a few snags. Would appreciate some mentor's help with the following:

- refactoring out the cw-storage-plus elements; specifically the compound key mapping and range iteration functions
- working with secret-cosmwasm-std::Decimal type does not support a subtraction operator, so a workaround is needed in some functions
- understanding what data to include in the HandleResponses
- how to effectively use imports from the cw3 crate. I get issues related to JsonSchema traits unless I copy/paste the structs and enums locally, which defeats the purpose of having a reference library crate.
